# Generated by Django 4.2.7 on 2025-06-19 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateNFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_id', models.CharField(max_length=255)),
                ('asset_id', models.CharField(max_length=255, unique=True)),
                ('asset_name', models.CharField(max_length=255, unique=True)),
                ('tx_hash', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('minted_at', models.DateTimeField(auto_now_add=True)),
                ('certificate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificate_nfts', to='api.certificate')),
            ],
            options={
                'verbose_name': 'Certificate NFT',
                'verbose_name_plural': 'Certificate NFTs',
                'ordering': ['-minted_at'],
            },
        ),
    ]
