# Generated by Django 4.2.7 on 2025-08-13 13:36

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_quiz_quizquestion_quizquestionoption_quizattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, default='/static/images/defaults/default-category.jpg', null=True, upload_to=api.utils.course_file_upload_path),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=api.utils.course_file_upload_path),
        ),
        migrations.AlterField(
            model_name='course',
            name='file',
            field=models.FileField(blank=True, default='/static/images/defaults/default-course.jpg', null=True, upload_to=api.utils.course_video_upload_path),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, default='/static/images/defaults/default-course.jpg', null=True, upload_to=api.utils.course_image_upload_path),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.FileField(blank=True, default='/static/images/defaults/avatars/default-avatar.jpg', null=True, upload_to=api.utils.course_file_upload_path),
        ),
        migrations.AlterField(
            model_name='variantitem',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to=api.utils.course_video_upload_path),
        ),
    ]
