# Generated by Django 4.2.7 on 2025-08-13 13:36

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, default='/static/images/defaults/avatars/default-avatar.jpg', null=True, upload_to=userauths.models.user_avatar_upload_path),
        ),
    ]
